#!/usr/bin/env bash

session=$(find ~/video/ ~/personal/ ~/work ~/.dotfiles -mindepth 1 -maxdepth 1 -type d 2>/dev/null | fzf)
session_name=$(basename "$session")

if ! tmux hassession -t "$session_name" 2>/dev/null ; then
  tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
